# Generated by Django 4.1.1 on 2022-10-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_remove_contact_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phonenumber',
            field=models.CharField(default=12345, max_length=11),
            preserve_default=False,
        ),
    ]
