# Generated by Django 4.1.1 on 2022-10-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_contact_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=254)),
                ('Gender', models.CharField(max_length=15)),
                ('PhoneNumber', models.CharField(max_length=11)),
                ('DOB', models.DateField()),
                ('SelectMembershipplan', models.CharField(max_length=30)),
                ('SelectTrainer', models.CharField(max_length=45)),
                ('Reference', models.CharField(max_length=45)),
                ('Address', models.TextField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=185)),
                ('price', models.IntegerField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=11)),
                ('salary', models.IntegerField(max_length=55)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
