# Generated by Django 4.1.1 on 2022-10-04 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_enrollment_duedate_enrollment_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='Reference',
        ),
    ]
