# Generated by Django 4.1.1 on 2022-11-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_remove_enrollment_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('image', models.ImageField(upload_to='Images', verbose_name='Upload Image')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
